name = "ForSudoku"
description= "Generates and solves sudokus"
version = "1.0.0"
license    = "GPL-3.0-or-later"
author = "vmagnin, nbehrnd"
copyright = "Copyright 2006-2024, vmagnin & nbehrnd"
maintainer = "https://github.com/vmagnin/ForSudoku/issues"
homepage   = "https://github.com/vmagnin/ForSudoku"
categories = ["games"]
keywords   = ["Fortran", "fpm", "sudoku"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[test]
program = "test/check.f90"
